using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace EmployeePortal.Migrations
{
    public partial class FirstMigration : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "pmast",
                columns: table => new
                {
                    EMPNO = table.Column<string>(unicode: false, maxLength: 6, nullable: false),
                    EMP_CODE = table.Column<string>(unicode: false, maxLength: 12, nullable: false),
                    NAME = table.Column<string>(unicode: false, maxLength: 50, nullable: false),
                    INAME = table.Column<string>(unicode: false, maxLength: 3, nullable: false),
                    ADD1 = table.Column<string>(unicode: false, maxLength: 50, nullable: false),
                    ADD2 = table.Column<string>(unicode: false, maxLength: 50, nullable: false),
                    POSTCODE = table.Column<string>(unicode: false, maxLength: 6, nullable: false),
                    TOWN = table.Column<string>(unicode: false, maxLength: 15, nullable: false),
                    STATE = table.Column<string>(unicode: false, maxLength: 15, nullable: false),
                    PHONE = table.Column<string>(unicode: false, maxLength: 24, nullable: false),
                    DBIRTH = table.Column<DateTime>(type: "datetime", nullable: false),
                    NRIC = table.Column<string>(unicode: false, maxLength: 15, nullable: false),
                    NRICN = table.Column<string>(unicode: false, maxLength: 22, nullable: false),
                    ICCOLOR = table.Column<string>(unicode: false, maxLength: 3, nullable: false),
                    NATIONAL = table.Column<string>(unicode: false, maxLength: 2, nullable: false),
                    PASSPORT = table.Column<string>(unicode: false, maxLength: 12, nullable: false),
                    SEX = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    MSTATUS = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    MSTATUSOD = table.Column<string>(unicode: false, maxLength: 15, nullable: false),
                    RACE = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    B_PUTRA = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    EDU = table.Column<string>(unicode: false, maxLength: 30, nullable: false),
                    EXP = table.Column<string>(unicode: false, maxLength: 30, nullable: false),
                    SNAME = table.Column<string>(unicode: false, maxLength: 30, nullable: false),
                    SNRIC = table.Column<string>(unicode: false, maxLength: 22, nullable: false),
                    SITBRANCH = table.Column<string>(unicode: false, maxLength: 15, nullable: false),
                    ISKERJA = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    TX_DED_SP = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    NUM_CHILD = table.Column<decimal>(type: "numeric(4, 1)", nullable: false),
                    NUMCHILD = table.Column<int>(nullable: false),
                    NOCHILD = table.Column<int>(nullable: false),
                    ECONTACT = table.Column<string>(unicode: false, maxLength: 24, nullable: false),
                    ETELNO = table.Column<string>(unicode: false, maxLength: 24, nullable: false),
                    EADD1 = table.Column<string>(unicode: false, maxLength: 40, nullable: false),
                    EADD2 = table.Column<string>(unicode: false, maxLength: 40, nullable: false),
                    EADD3 = table.Column<string>(unicode: false, maxLength: 40, nullable: false),
                    CATEGORY = table.Column<string>(unicode: false, maxLength: 10, nullable: false),
                    SOURCE = table.Column<string>(unicode: false, maxLength: 10, nullable: false),
                    PLINENO = table.Column<string>(unicode: false, maxLength: 10, nullable: false),
                    JTITLE = table.Column<string>(unicode: false, maxLength: 40, nullable: false),
                    DCOMM = table.Column<DateTime>(type: "datetime", nullable: false),
                    DCONFIRM = table.Column<DateTime>(type: "datetime", nullable: false),
                    DPROMOTE = table.Column<DateTime>(type: "datetime", nullable: false),
                    DRESIGN = table.Column<DateTime>(type: "datetime", nullable: false),
                    R_STATU = table.Column<string>(unicode: false, maxLength: 2, nullable: false),
                    PR_NUM = table.Column<string>(unicode: false, maxLength: 20, nullable: false),
                    PR_FROM = table.Column<DateTime>(type: "datetime", nullable: false),
                    IMIGRANO = table.Column<string>(unicode: false, maxLength: 20, nullable: false),
                    WPERMIT = table.Column<string>(unicode: false, maxLength: 20, nullable: false),
                    WP_FROM = table.Column<DateTime>(type: "datetime", nullable: false),
                    WP_TO = table.Column<DateTime>(type: "datetime", nullable: false),
                    EMPPASS = table.Column<string>(unicode: false, maxLength: 15, nullable: false),
                    FWLEVYTBL = table.Column<string>(unicode: false, maxLength: 2, nullable: false),
                    FWLEVYMTD = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    FWLEVYADJ = table.Column<decimal>(type: "numeric(6, 2)", nullable: false),
                    EPFNO = table.Column<string>(unicode: false, maxLength: 12, nullable: false),
                    EPFNK = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    EPFTBL = table.Column<string>(unicode: false, maxLength: 2, nullable: false),
                    EPFCAT = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    CPF_CEILI = table.Column<int>(nullable: false),
                    EPF_FYEE = table.Column<string>(unicode: false, maxLength: 60, nullable: false),
                    EPF_FYER = table.Column<string>(unicode: false, maxLength: 60, nullable: false),
                    EPGNO = table.Column<string>(unicode: false, maxLength: 15, nullable: false),
                    EPGTBL = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    EPGCAT = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    SOCSONO = table.Column<string>(unicode: false, maxLength: 15, nullable: false),
                    SOCSOTBL = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    SOCSOCAT = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    SOCSOIC = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    ICINSSOCNO = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    SOCSOINIT = table.Column<string>(unicode: false, maxLength: 5, nullable: false),
                    MUSTPR_SOC = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    SOASONO = table.Column<string>(unicode: false, maxLength: 15, nullable: false),
                    SOASOTBL = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    SOASOCAT = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    SOBSONO = table.Column<string>(unicode: false, maxLength: 15, nullable: false),
                    SOBSOTBL = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    SOBSOCAT = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    SODSONO = table.Column<string>(unicode: false, maxLength: 15, nullable: false),
                    SODSOTBL = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    SODSOCAT = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    SOESONO = table.Column<string>(unicode: false, maxLength: 15, nullable: false),
                    SOESOTBL = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    SOESOCAT = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    UNIONNO = table.Column<string>(unicode: false, maxLength: 15, nullable: false),
                    UNIONTBL = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    UNIONCAT = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    UNEMPITBL = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    MEDITBL = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    ITAXNO = table.Column<string>(unicode: false, maxLength: 20, nullable: false),
                    ITAXNOKI = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    ITAXTBL = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    ITAXCAT = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    CP8DGRP = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    CP8DGRPI = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    EMP_STATUS = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    EMP_TYPE = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    EA_GRP_SN = table.Column<string>(unicode: false, maxLength: 12, nullable: false),
                    EA_SN = table.Column<string>(unicode: false, maxLength: 10, nullable: false),
                    ITAXBRAN = table.Column<string>(unicode: false, maxLength: 15, nullable: false),
                    BANKCODE = table.Column<string>(unicode: false, maxLength: 12, nullable: false),
                    BRANCODE = table.Column<string>(unicode: false, maxLength: 12, nullable: false),
                    BANKACCNO = table.Column<string>(unicode: false, maxLength: 20, nullable: false),
                    BANKCAT = table.Column<string>(unicode: false, maxLength: 2, nullable: false),
                    BANKPMODE = table.Column<string>(unicode: false, maxLength: 30, nullable: false),
                    BRATE = table.Column<decimal>(type: "numeric(13, 3)", nullable: false),
                    BRATE_LM = table.Column<decimal>(type: "numeric(13, 3)", nullable: false),
                    INC_AMT = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    INC_DATE = table.Column<DateTime>(type: "datetime", nullable: false),
                    M_INC_AMT = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    M_INC_DATE = table.Column<DateTime>(type: "datetime", nullable: false),
                    PAYRTYPE = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    PAYMETH = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    PAYSTATUS = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    CONFID = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    CONTRACT = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    CONTRACT_F = table.Column<DateTime>(type: "datetime", nullable: false),
                    CONTRACT_T = table.Column<DateTime>(type: "datetime", nullable: false),
                    DBAW101 = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    DBAW102 = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    DBAW103 = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    DBAW104 = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    DBAW105 = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    DBAW106 = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    DBAW107 = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    DBAW108 = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    DBAW109 = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    DBAW110 = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    DBAW111 = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    DBAW112 = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    DBAW113 = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    DBAW114 = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    DBAW115 = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    DBAW116 = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    DBAW117 = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    DBDED101 = table.Column<decimal>(type: "numeric(10, 2)", nullable: false),
                    DBDED102 = table.Column<decimal>(type: "numeric(10, 2)", nullable: false),
                    DBDED103 = table.Column<decimal>(type: "numeric(10, 2)", nullable: false),
                    DBDED104 = table.Column<decimal>(type: "numeric(10, 2)", nullable: false),
                    DBDED105 = table.Column<decimal>(type: "numeric(10, 2)", nullable: false),
                    DBDED106 = table.Column<decimal>(type: "numeric(10, 2)", nullable: false),
                    DBDED107 = table.Column<decimal>(type: "numeric(10, 2)", nullable: false),
                    DBDED108 = table.Column<decimal>(type: "numeric(10, 2)", nullable: false),
                    DBDED109 = table.Column<decimal>(type: "numeric(10, 2)", nullable: false),
                    DBDED110 = table.Column<decimal>(type: "numeric(10, 2)", nullable: false),
                    DBDED111 = table.Column<decimal>(type: "numeric(10, 2)", nullable: false),
                    DBDED112 = table.Column<decimal>(type: "numeric(10, 2)", nullable: false),
                    DBDED113 = table.Column<decimal>(type: "numeric(10, 2)", nullable: false),
                    DBDED114 = table.Column<decimal>(type: "numeric(10, 2)", nullable: false),
                    DBDED115 = table.Column<decimal>(type: "numeric(10, 2)", nullable: false),
                    SHIFTTBL = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    ALBF = table.Column<decimal>(type: "numeric(9, 2)", nullable: false),
                    ALALL = table.Column<decimal>(type: "numeric(9, 2)", nullable: false),
                    ALADJ = table.Column<decimal>(type: "numeric(9, 2)", nullable: false),
                    ALCLA = table.Column<decimal>(type: "numeric(9, 2)", nullable: false),
                    LVETOCASH = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    MCALL = table.Column<decimal>(type: "numeric(9, 2)", nullable: false),
                    ALMCTBL = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    MFUNDALL = table.Column<decimal>(type: "numeric(10, 2)", nullable: false),
                    DFUNDALL = table.Column<decimal>(type: "numeric(10, 2)", nullable: false),
                    NOADVDAY = table.Column<decimal>(type: "numeric(8, 2)", nullable: false),
                    EPF1HD = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    EPFBYER = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    EPG1HD = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    EPGBYER = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    SOCSO1HD = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    SOASOBYER = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    SOBSOBYER = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    SOCSOBYER = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    SODSOBYER = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    SOESOBYER = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    UNIONBYER = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    PCB1HD = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    SOASO1HD = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    SOBSO1HD = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    SODSO1HD = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    SOESO1HD = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    UNION1HD = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    STAT11HD = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    EPFBRINSBP = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    WITHPCB = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    WITHBOPCB = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    WITHCOPCB = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    WITHHRDF = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    PCBBYER = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    NM_PCB = table.Column<int>(nullable: false),
                    PBONUS_MTH = table.Column<int>(nullable: false),
                    OTCODE = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    WHTBL = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    OTTBL = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    OT_MAXPAY = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    EPFIC = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    NPPM = table.Column<int>(nullable: false),
                    WEEKPAY = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    OTRATERC = table.Column<string>(unicode: false, maxLength: 2, nullable: false),
                    HRP_BRATE = table.Column<decimal>(type: "numeric(13, 4)", nullable: false),
                    HRP_LM = table.Column<decimal>(type: "numeric(13, 4)", nullable: false),
                    HRP_TM = table.Column<decimal>(type: "numeric(13, 4)", nullable: false),
                    ORP_LM = table.Column<decimal>(type: "numeric(13, 4)", nullable: false),
                    ORP_TM = table.Column<decimal>(type: "numeric(13, 4)", nullable: false),
                    DAYPMTH = table.Column<decimal>(type: "numeric(5, 2)", nullable: false),
                    DEDMEM111 = table.Column<string>(unicode: false, maxLength: 20, nullable: false),
                    DEDMEM112 = table.Column<string>(unicode: false, maxLength: 20, nullable: false),
                    DEDMEM113 = table.Column<string>(unicode: false, maxLength: 20, nullable: false),
                    DEDMEM114 = table.Column<string>(unicode: false, maxLength: 20, nullable: false),
                    DEDMEM115 = table.Column<string>(unicode: false, maxLength: 20, nullable: false),
                    TEMPFIG1 = table.Column<decimal>(type: "numeric(14, 2)", nullable: false),
                    TEMPFIG2 = table.Column<decimal>(type: "numeric(14, 2)", nullable: false),
                    TEMPFIG3 = table.Column<decimal>(type: "numeric(14, 2)", nullable: false),
                    TEMPFIG4 = table.Column<decimal>(type: "numeric(14, 2)", nullable: false),
                    LY_D_TXAMT = table.Column<decimal>(type: "numeric(15, 2)", nullable: false),
                    LY_D_EPF = table.Column<decimal>(type: "numeric(15, 2)", nullable: false),
                    TEMPSTR1 = table.Column<string>(unicode: false, maxLength: 30, nullable: false),
                    PRN_EA = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    PRN_IR8S = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    REMARK = table.Column<string>(unicode: false, maxLength: 100, nullable: false),
                    PHOTODIR = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    PHOTO = table.Column<string>(unicode: false, nullable: false),
                    BONUS = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    BONUSTOLY = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    BONUSFRNY = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    COMM = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    EXTRA = table.Column<decimal>(type: "numeric(12, 2)", nullable: false),
                    BANKIC = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    WORKGRPID = table.Column<string>(unicode: false, maxLength: 8, nullable: false),
                    RESTWKDAY = table.Column<int>(nullable: false),
                    BADGENO = table.Column<string>(unicode: false, maxLength: 10, nullable: false),
                    PHONE2 = table.Column<string>(unicode: false, maxLength: 24, nullable: false),
                    EMAIL = table.Column<string>(unicode: false, maxLength: 50, nullable: false),
                    JOBCODE = table.Column<string>(unicode: false, maxLength: 4, nullable: false),
                    DEPTCODE = table.Column<string>(unicode: false, maxLength: 10, nullable: false),
                    RELCODE = table.Column<string>(unicode: false, maxLength: 2, nullable: false),
                    TRANCODE = table.Column<string>(unicode: false, maxLength: 2, nullable: false),
                    JSTACODE = table.Column<string>(unicode: false, maxLength: 2, nullable: false),
                    BRCODE = table.Column<string>(unicode: false, maxLength: 4, nullable: false),
                    DPASSPORT = table.Column<DateTime>(type: "datetime", nullable: false),
                    EMERPHONE = table.Column<string>(unicode: false, maxLength: 24, nullable: false),
                    EMERRSHIP = table.Column<string>(unicode: false, maxLength: 15, nullable: false),
                    JFUNCTION = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    LSCHMCODE = table.Column<string>(unicode: false, maxLength: 4, nullable: false),
                    CSCHMCODE = table.Column<string>(unicode: false, maxLength: 4, nullable: false),
                    DATEENTER = table.Column<DateTime>(type: "datetime", nullable: false),
                    KEYUSER = table.Column<string>(unicode: false, maxLength: 6, nullable: false),
                    ALBAL = table.Column<decimal>(type: "numeric(6, 2)", nullable: false),
                    MCBAL = table.Column<decimal>(type: "numeric(6, 2)", nullable: false),
                    FINNO = table.Column<string>(unicode: false, maxLength: 21, nullable: false),
                    CREATED_ON = table.Column<DateTime>(type: "datetime", nullable: false),
                    UPDATED_ON = table.Column<DateTime>(type: "datetime", nullable: false),
                    SU = table.Column<bool>(nullable: false),
                    DU = table.Column<bool>(nullable: false),
                    ADDRTYPE = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    DIRFSET = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    COUNTRYC = table.Column<string>(unicode: false, maxLength: 2, nullable: false),
                    PR_RATE = table.Column<string>(unicode: false, maxLength: 2, nullable: false),
                    MEPS = table.Column<string>(unicode: false, maxLength: 20, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_pmast", x => x.EMPNO);
                });

            migrationBuilder.CreateTable(
                name: "family",
                columns: table => new
                {
                    NRICNO = table.Column<string>(unicode: false, maxLength: 15, nullable: false),
                    EMPNO = table.Column<string>(unicode: false, maxLength: 6, nullable: false),
                    MEMNAME = table.Column<string>(unicode: false, maxLength: 45, nullable: false),
                    SEX = table.Column<string>(unicode: false, maxLength: 1, nullable: false),
                    DATEBIRTH = table.Column<DateTime>(type: "date", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_family_1", x => x.NRICNO);
                    table.ForeignKey(
                        name: "FK_family_pmast",
                        column: x => x.EMPNO,
                        principalTable: "pmast",
                        principalColumn: "EMPNO",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_family_EMPNO",
                table: "family",
                column: "EMPNO");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "family");

            migrationBuilder.DropTable(
                name: "pmast");
        }
    }
}
