using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AdminPanelTest.Models
{
    public partial class Pmast
    {
        public Pmast()
        {
            Family = new HashSet<Family>();
        }
        [Key]
        public string Empno { get; set; }

        public string EmpCode { get; set; }

        [DisplayName("First Name")]
        public string Name { get; set; }
        public string Iname { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string Postcode { get; set; }
        public string Town { get; set; }
        public string State { get; set; }
        public string Phone { get; set; }
        public DateTime? Dbirth { get; set; }
        public string Nric { get; set; }
        public string Nricn { get; set; }
        public string Iccolor { get; set; }
        public string National { get; set; }
        public string Passport { get; set; }
        public string Sex { get; set; }
        public string Mstatus { get; set; }
        public string Mstatusod { get; set; }
        public string Race { get; set; }
        public string BPutra { get; set; }
        public string Edu { get; set; }
        public string Exp { get; set; }
        public string Sname { get; set; }
        public string Snric { get; set; }
        public string Sitbranch { get; set; }
        public string Iskerja { get; set; }
        public string TxDedSp { get; set; }
        public decimal? NumChild { get; set; }
        public int? Numchild1 { get; set; }
        public int? Nochild { get; set; }
        public string Econtact { get; set; }
        public string Etelno { get; set; }
        public string Eadd1 { get; set; }
        public string Eadd2 { get; set; }
        public string Eadd3 { get; set; }
        public string Category { get; set; }
        public string Source { get; set; }
        public string Plineno { get; set; }
        public string Jtitle { get; set; }
        public DateTime? Dcomm { get; set; }
        public DateTime? Dconfirm { get; set; }
        public DateTime? Dpromote { get; set; }
        public DateTime? Dresign { get; set; }
        public string RStatu { get; set; }
        public string PrNum { get; set; }
        public DateTime? PrFrom { get; set; }
        public string Imigrano { get; set; }
        public string Wpermit { get; set; }
        public DateTime? WpFrom { get; set; }
        public DateTime? WpTo { get; set; }
        public string Emppass { get; set; }
        public string Fwlevytbl { get; set; }
        public string Fwlevymtd { get; set; }
        public decimal? Fwlevyadj { get; set; }
        public string Epfno { get; set; }
        public string Epfnk { get; set; }
        public string Epftbl { get; set; }
        public string Epfcat { get; set; }
        public int? CpfCeili { get; set; }
        public string EpfFyee { get; set; }
        public string EpfFyer { get; set; }
        public string Epgno { get; set; }
        public string Epgtbl { get; set; }
        public string Epgcat { get; set; }
        public string Socsono { get; set; }
        public string Socsotbl { get; set; }
        public string Socsocat { get; set; }
        public string Socsoic { get; set; }
        public string Icinssocno { get; set; }
        public string Socsoinit { get; set; }
        public string MustprSoc { get; set; }
        public string Soasono { get; set; }
        public string Soasotbl { get; set; }
        public string Soasocat { get; set; }
        public string Sobsono { get; set; }
        public string Sobsotbl { get; set; }
        public string Sobsocat { get; set; }
        public string Sodsono { get; set; }
        public string Sodsotbl { get; set; }
        public string Sodsocat { get; set; }
        public string Soesono { get; set; }
        public string Soesotbl { get; set; }
        public string Soesocat { get; set; }
        public string Unionno { get; set; }
        public string Uniontbl { get; set; }
        public string Unioncat { get; set; }
        public string Unempitbl { get; set; }
        public string Meditbl { get; set; }
        public string Itaxno { get; set; }
        public string Itaxnoki { get; set; }
        public string Itaxtbl { get; set; }
        public string Itaxcat { get; set; }
        public string Cp8dgrp { get; set; }
        public string Cp8dgrpi { get; set; }
        public string EmpStatus { get; set; }
        public string EmpType { get; set; }
        public string EaGrpSn { get; set; }
        public string EaSn { get; set; }
        public string Itaxbran { get; set; }
        public string Bankcode { get; set; }
        public string Brancode { get; set; }
        public string Bankaccno { get; set; }
        public string Bankcat { get; set; }
        public string Bankpmode { get; set; }
        public decimal? Brate { get; set; }
        public decimal? BrateLm { get; set; }
        public decimal? IncAmt { get; set; }
        public DateTime? IncDate { get; set; }
        public decimal? MIncAmt { get; set; }
        public DateTime? MIncDate { get; set; }
        public string Payrtype { get; set; }
        public string Paymeth { get; set; }
        public string Paystatus { get; set; }
        public string Confid { get; set; }
        public string Contract { get; set; }
        public DateTime? ContractF { get; set; }
        public DateTime? ContractT { get; set; }
        public decimal? Dbaw101 { get; set; }
        public decimal? Dbaw102 { get; set; }
        public decimal? Dbaw103 { get; set; }
        public decimal? Dbaw104 { get; set; }
        public decimal? Dbaw105 { get; set; }
        public decimal? Dbaw106 { get; set; }
        public decimal? Dbaw107 { get; set; }
        public decimal? Dbaw108 { get; set; }
        public decimal? Dbaw109 { get; set; }
        public decimal? Dbaw110 { get; set; }
        public decimal? Dbaw111 { get; set; }
        public decimal? Dbaw112 { get; set; }
        public decimal? Dbaw113 { get; set; }
        public decimal? Dbaw114 { get; set; }
        public decimal? Dbaw115 { get; set; }
        public decimal? Dbaw116 { get; set; }
        public decimal? Dbaw117 { get; set; }
        public decimal? Dbded101 { get; set; }
        public decimal? Dbded102 { get; set; }
        public decimal? Dbded103 { get; set; }
        public decimal? Dbded104 { get; set; }
        public decimal? Dbded105 { get; set; }
        public decimal? Dbded106 { get; set; }
        public decimal? Dbded107 { get; set; }
        public decimal? Dbded108 { get; set; }
        public decimal? Dbded109 { get; set; }
        public decimal? Dbded110 { get; set; }
        public decimal? Dbded111 { get; set; }
        public decimal? Dbded112 { get; set; }
        public decimal? Dbded113 { get; set; }
        public decimal? Dbded114 { get; set; }
        public decimal? Dbded115 { get; set; }
        public string Shifttbl { get; set; }
        public decimal? Albf { get; set; }
        public decimal? Alall { get; set; }
        public decimal? Aladj { get; set; }
        public decimal? Alcla { get; set; }
        public decimal? Lvetocash { get; set; }
        public decimal? Mcall { get; set; }
        public string Almctbl { get; set; }
        public decimal? Mfundall { get; set; }
        public decimal? Dfundall { get; set; }
        public decimal? Noadvday { get; set; }
        public string Epf1hd { get; set; }
        public string Epfbyer { get; set; }
        public string Epg1hd { get; set; }
        public string Epgbyer { get; set; }
        public string Socso1hd { get; set; }
        public string Soasobyer { get; set; }
        public string Sobsobyer { get; set; }
        public string Socsobyer { get; set; }
        public string Sodsobyer { get; set; }
        public string Soesobyer { get; set; }
        public string Unionbyer { get; set; }
        public string Pcb1hd { get; set; }
        public string Soaso1hd { get; set; }
        public string Sobso1hd { get; set; }
        public string Sodso1hd { get; set; }
        public string Soeso1hd { get; set; }
        public string Union1hd { get; set; }
        public string Stat11hd { get; set; }
        public string Epfbrinsbp { get; set; }
        public string Withpcb { get; set; }
        public string Withbopcb { get; set; }
        public string Withcopcb { get; set; }
        public string Withhrdf { get; set; }
        public string Pcbbyer { get; set; }
        public int? NmPcb { get; set; }
        public int? PbonusMth { get; set; }
        public string Otcode { get; set; }
        public string Whtbl { get; set; }
        public string Ottbl { get; set; }
        public string OtMaxpay { get; set; }
        public string Epfic { get; set; }
        public int? Nppm { get; set; }
        public string Weekpay { get; set; }
        public string Otraterc { get; set; }
        public decimal? HrpBrate { get; set; }
        public decimal? HrpLm { get; set; }
        public decimal? HrpTm { get; set; }
        public decimal? OrpLm { get; set; }
        public decimal? OrpTm { get; set; }
        public decimal? Daypmth { get; set; }
        public string Dedmem111 { get; set; }
        public string Dedmem112 { get; set; }
        public string Dedmem113 { get; set; }
        public string Dedmem114 { get; set; }
        public string Dedmem115 { get; set; }
        public decimal? Tempfig1 { get; set; }
        public decimal? Tempfig2 { get; set; }
        public decimal? Tempfig3 { get; set; }
        public decimal? Tempfig4 { get; set; }
        public decimal? LyDTxamt { get; set; }
        public decimal? LyDEpf { get; set; }
        public string Tempstr1 { get; set; }
        public string PrnEa { get; set; }
        public string PrnIr8s { get; set; }
        public string Remark { get; set; }
        public string Photodir { get; set; }
        public string Photo { get; set; }
        public decimal? Bonus { get; set; }
        public decimal? Bonustoly { get; set; }
        public decimal? Bonusfrny { get; set; }
        public decimal? Comm { get; set; }
        public decimal? Extra { get; set; }
        public string Bankic { get; set; }
        public string Workgrpid { get; set; }
        public int? Restwkday { get; set; }
        public string Badgeno { get; set; }
        public string Phone2 { get; set; }
        public string Email { get; set; }
        public string Jobcode { get; set; }
        public string Deptcode { get; set; }
        public string Relcode { get; set; }
        public string Trancode { get; set; }
        public string Jstacode { get; set; }
        public string Brcode { get; set; }
        public DateTime? Dpassport { get; set; }
        public string Emerphone { get; set; }
        public string Emerrship { get; set; }
        public string Jfunction { get; set; }
        public string Lschmcode { get; set; }
        public string Cschmcode { get; set; }
        public DateTime? Dateenter { get; set; }
        public string Keyuser { get; set; }
        public decimal? Albal { get; set; }
        public decimal? Mcbal { get; set; }
        public string Finno { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public bool? Su { get; set; }
        public bool? Du { get; set; }
        public string Addrtype { get; set; }
        public string Dirfset { get; set; }
        public string Countryc { get; set; }
        public string PrRate { get; set; }
        public string Meps { get; set; }

        public virtual ICollection<Family> Family { get; set; }
    }
}
