// <auto-generated />
using System;
using EmployeePortal.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeePortal.Migrations
{
    [DbContext(typeof(bcckContext))]
    partial class bcckContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeePortal.Models.Family", b =>
                {
                    b.Property<string>("Nricno")
                        .HasColumnName("NRICNO")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<DateTime>("Datebirth")
                        .HasColumnName("DATEBIRTH")
                        .HasColumnType("date");

                    b.Property<string>("Empno")
                        .IsRequired()
                        .HasColumnName("EMPNO")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Memname")
                        .IsRequired()
                        .HasColumnName("MEMNAME")
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnName("SEX")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.HasKey("Nricno")
                        .HasName("PK_family_1");

                    b.HasIndex("Empno");

                    b.ToTable("family");
                });

            modelBuilder.Entity("EmployeePortal.Models.Pmast", b =>
                {
                    b.Property<string>("Empno")
                        .HasColumnName("EMPNO")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Add1")
                        .IsRequired()
                        .HasColumnName("ADD1")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Add2")
                        .IsRequired()
                        .HasColumnName("ADD2")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Addrtype")
                        .IsRequired()
                        .HasColumnName("ADDRTYPE")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<decimal>("Aladj")
                        .HasColumnName("ALADJ")
                        .HasColumnType("numeric(9, 2)");

                    b.Property<decimal>("Alall")
                        .HasColumnName("ALALL")
                        .HasColumnType("numeric(9, 2)");

                    b.Property<decimal>("Albal")
                        .HasColumnName("ALBAL")
                        .HasColumnType("numeric(6, 2)");

                    b.Property<decimal>("Albf")
                        .HasColumnName("ALBF")
                        .HasColumnType("numeric(9, 2)");

                    b.Property<decimal>("Alcla")
                        .HasColumnName("ALCLA")
                        .HasColumnType("numeric(9, 2)");

                    b.Property<string>("Almctbl")
                        .IsRequired()
                        .HasColumnName("ALMCTBL")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("BPutra")
                        .IsRequired()
                        .HasColumnName("B_PUTRA")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Badgeno")
                        .IsRequired()
                        .HasColumnName("BADGENO")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Bankaccno")
                        .IsRequired()
                        .HasColumnName("BANKACCNO")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Bankcat")
                        .IsRequired()
                        .HasColumnName("BANKCAT")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Bankcode")
                        .IsRequired()
                        .HasColumnName("BANKCODE")
                        .HasMaxLength(12)
                        .IsUnicode(false);

                    b.Property<string>("Bankic")
                        .IsRequired()
                        .HasColumnName("BANKIC")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Bankpmode")
                        .IsRequired()
                        .HasColumnName("BANKPMODE")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<decimal>("Bonus")
                        .HasColumnName("BONUS")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal>("Bonusfrny")
                        .HasColumnName("BONUSFRNY")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal>("Bonustoly")
                        .HasColumnName("BONUSTOLY")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<string>("Brancode")
                        .IsRequired()
                        .HasColumnName("BRANCODE")
                        .HasMaxLength(12)
                        .IsUnicode(false);

                    b.Property<decimal>("Brate")
                        .HasColumnName("BRATE")
                        .HasColumnType("numeric(13, 3)");

                    b.Property<decimal>("BrateLm")
                        .HasColumnName("BRATE_LM")
                        .HasColumnType("numeric(13, 3)");

                    b.Property<string>("Brcode")
                        .IsRequired()
                        .HasColumnName("BRCODE")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnName("CATEGORY")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<decimal>("Comm")
                        .HasColumnName("COMM")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<string>("Confid")
                        .IsRequired()
                        .HasColumnName("CONFID")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Contract")
                        .IsRequired()
                        .HasColumnName("CONTRACT")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime>("ContractF")
                        .HasColumnName("CONTRACT_F")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ContractT")
                        .HasColumnName("CONTRACT_T")
                        .HasColumnType("datetime");

                    b.Property<string>("Countryc")
                        .IsRequired()
                        .HasColumnName("COUNTRYC")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Cp8dgrp")
                        .IsRequired()
                        .HasColumnName("CP8DGRP")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Cp8dgrpi")
                        .IsRequired()
                        .HasColumnName("CP8DGRPI")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<int>("CpfCeili")
                        .HasColumnName("CPF_CEILI");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnName("CREATED_ON")
                        .HasColumnType("datetime");

                    b.Property<string>("Cschmcode")
                        .IsRequired()
                        .HasColumnName("CSCHMCODE")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<DateTime>("Dateenter")
                        .HasColumnName("DATEENTER")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Daypmth")
                        .HasColumnName("DAYPMTH")
                        .HasColumnType("numeric(5, 2)");

                    b.Property<decimal>("Dbaw101")
                        .HasColumnName("DBAW101")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal>("Dbaw102")
                        .HasColumnName("DBAW102")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal>("Dbaw103")
                        .HasColumnName("DBAW103")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal>("Dbaw104")
                        .HasColumnName("DBAW104")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal>("Dbaw105")
                        .HasColumnName("DBAW105")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal>("Dbaw106")
                        .HasColumnName("DBAW106")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal>("Dbaw107")
                        .HasColumnName("DBAW107")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal>("Dbaw108")
                        .HasColumnName("DBAW108")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal>("Dbaw109")
                        .HasColumnName("DBAW109")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal>("Dbaw110")
                        .HasColumnName("DBAW110")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal>("Dbaw111")
                        .HasColumnName("DBAW111")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal>("Dbaw112")
                        .HasColumnName("DBAW112")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal>("Dbaw113")
                        .HasColumnName("DBAW113")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal>("Dbaw114")
                        .HasColumnName("DBAW114")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal>("Dbaw115")
                        .HasColumnName("DBAW115")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal>("Dbaw116")
                        .HasColumnName("DBAW116")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal>("Dbaw117")
                        .HasColumnName("DBAW117")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal>("Dbded101")
                        .HasColumnName("DBDED101")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal>("Dbded102")
                        .HasColumnName("DBDED102")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal>("Dbded103")
                        .HasColumnName("DBDED103")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal>("Dbded104")
                        .HasColumnName("DBDED104")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal>("Dbded105")
                        .HasColumnName("DBDED105")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal>("Dbded106")
                        .HasColumnName("DBDED106")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal>("Dbded107")
                        .HasColumnName("DBDED107")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal>("Dbded108")
                        .HasColumnName("DBDED108")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal>("Dbded109")
                        .HasColumnName("DBDED109")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal>("Dbded110")
                        .HasColumnName("DBDED110")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal>("Dbded111")
                        .HasColumnName("DBDED111")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal>("Dbded112")
                        .HasColumnName("DBDED112")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal>("Dbded113")
                        .HasColumnName("DBDED113")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal>("Dbded114")
                        .HasColumnName("DBDED114")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<decimal>("Dbded115")
                        .HasColumnName("DBDED115")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<DateTime>("Dbirth")
                        .HasColumnName("DBIRTH")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Dcomm")
                        .HasColumnName("DCOMM")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Dconfirm")
                        .HasColumnName("DCONFIRM")
                        .HasColumnType("datetime");

                    b.Property<string>("Dedmem111")
                        .IsRequired()
                        .HasColumnName("DEDMEM111")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Dedmem112")
                        .IsRequired()
                        .HasColumnName("DEDMEM112")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Dedmem113")
                        .IsRequired()
                        .HasColumnName("DEDMEM113")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Dedmem114")
                        .IsRequired()
                        .HasColumnName("DEDMEM114")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Dedmem115")
                        .IsRequired()
                        .HasColumnName("DEDMEM115")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Deptcode")
                        .IsRequired()
                        .HasColumnName("DEPTCODE")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<decimal>("Dfundall")
                        .HasColumnName("DFUNDALL")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<string>("Dirfset")
                        .IsRequired()
                        .HasColumnName("DIRFSET")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime>("Dpassport")
                        .HasColumnName("DPASSPORT")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Dpromote")
                        .HasColumnName("DPROMOTE")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Dresign")
                        .HasColumnName("DRESIGN")
                        .HasColumnType("datetime");

                    b.Property<bool>("Du")
                        .HasColumnName("DU");

                    b.Property<string>("EaGrpSn")
                        .IsRequired()
                        .HasColumnName("EA_GRP_SN")
                        .HasMaxLength(12)
                        .IsUnicode(false);

                    b.Property<string>("EaSn")
                        .IsRequired()
                        .HasColumnName("EA_SN")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Eadd1")
                        .IsRequired()
                        .HasColumnName("EADD1")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("Eadd2")
                        .IsRequired()
                        .HasColumnName("EADD2")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("Eadd3")
                        .IsRequired()
                        .HasColumnName("EADD3")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("Econtact")
                        .IsRequired()
                        .HasColumnName("ECONTACT")
                        .HasMaxLength(24)
                        .IsUnicode(false);

                    b.Property<string>("Edu")
                        .IsRequired()
                        .HasColumnName("EDU")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("EMAIL")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Emerphone")
                        .IsRequired()
                        .HasColumnName("EMERPHONE")
                        .HasMaxLength(24)
                        .IsUnicode(false);

                    b.Property<string>("Emerrship")
                        .IsRequired()
                        .HasColumnName("EMERRSHIP")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("EmpCode")
                        .IsRequired()
                        .HasColumnName("EMP_CODE")
                        .HasMaxLength(12)
                        .IsUnicode(false);

                    b.Property<string>("EmpStatus")
                        .IsRequired()
                        .HasColumnName("EMP_STATUS")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("EmpType")
                        .IsRequired()
                        .HasColumnName("EMP_TYPE")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Emppass")
                        .IsRequired()
                        .HasColumnName("EMPPASS")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("Epf1hd")
                        .IsRequired()
                        .HasColumnName("EPF1HD")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("EpfFyee")
                        .IsRequired()
                        .HasColumnName("EPF_FYEE")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<string>("EpfFyer")
                        .IsRequired()
                        .HasColumnName("EPF_FYER")
                        .HasMaxLength(60)
                        .IsUnicode(false);

                    b.Property<string>("Epfbrinsbp")
                        .IsRequired()
                        .HasColumnName("EPFBRINSBP")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Epfbyer")
                        .IsRequired()
                        .HasColumnName("EPFBYER")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Epfcat")
                        .IsRequired()
                        .HasColumnName("EPFCAT")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Epfic")
                        .IsRequired()
                        .HasColumnName("EPFIC")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Epfnk")
                        .IsRequired()
                        .HasColumnName("EPFNK")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Epfno")
                        .IsRequired()
                        .HasColumnName("EPFNO")
                        .HasMaxLength(12)
                        .IsUnicode(false);

                    b.Property<string>("Epftbl")
                        .IsRequired()
                        .HasColumnName("EPFTBL")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Epg1hd")
                        .IsRequired()
                        .HasColumnName("EPG1HD")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Epgbyer")
                        .IsRequired()
                        .HasColumnName("EPGBYER")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Epgcat")
                        .IsRequired()
                        .HasColumnName("EPGCAT")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Epgno")
                        .IsRequired()
                        .HasColumnName("EPGNO")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("Epgtbl")
                        .IsRequired()
                        .HasColumnName("EPGTBL")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Etelno")
                        .IsRequired()
                        .HasColumnName("ETELNO")
                        .HasMaxLength(24)
                        .IsUnicode(false);

                    b.Property<string>("Exp")
                        .IsRequired()
                        .HasColumnName("EXP")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<decimal>("Extra")
                        .HasColumnName("EXTRA")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<string>("Finno")
                        .IsRequired()
                        .HasColumnName("FINNO")
                        .HasMaxLength(21)
                        .IsUnicode(false);

                    b.Property<decimal>("Fwlevyadj")
                        .HasColumnName("FWLEVYADJ")
                        .HasColumnType("numeric(6, 2)");

                    b.Property<string>("Fwlevymtd")
                        .IsRequired()
                        .HasColumnName("FWLEVYMTD")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Fwlevytbl")
                        .IsRequired()
                        .HasColumnName("FWLEVYTBL")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<decimal>("HrpBrate")
                        .HasColumnName("HRP_BRATE")
                        .HasColumnType("numeric(13, 4)");

                    b.Property<decimal>("HrpLm")
                        .HasColumnName("HRP_LM")
                        .HasColumnType("numeric(13, 4)");

                    b.Property<decimal>("HrpTm")
                        .HasColumnName("HRP_TM")
                        .HasColumnType("numeric(13, 4)");

                    b.Property<string>("Iccolor")
                        .IsRequired()
                        .HasColumnName("ICCOLOR")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<string>("Icinssocno")
                        .IsRequired()
                        .HasColumnName("ICINSSOCNO")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Imigrano")
                        .IsRequired()
                        .HasColumnName("IMIGRANO")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Iname")
                        .IsRequired()
                        .HasColumnName("INAME")
                        .HasMaxLength(3)
                        .IsUnicode(false);

                    b.Property<decimal>("IncAmt")
                        .HasColumnName("INC_AMT")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<DateTime>("IncDate")
                        .HasColumnName("INC_DATE")
                        .HasColumnType("datetime");

                    b.Property<string>("Iskerja")
                        .IsRequired()
                        .HasColumnName("ISKERJA")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Itaxbran")
                        .IsRequired()
                        .HasColumnName("ITAXBRAN")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("Itaxcat")
                        .IsRequired()
                        .HasColumnName("ITAXCAT")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Itaxno")
                        .IsRequired()
                        .HasColumnName("ITAXNO")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Itaxnoki")
                        .IsRequired()
                        .HasColumnName("ITAXNOKI")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Itaxtbl")
                        .IsRequired()
                        .HasColumnName("ITAXTBL")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Jfunction")
                        .IsRequired()
                        .HasColumnName("JFUNCTION")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Jobcode")
                        .IsRequired()
                        .HasColumnName("JOBCODE")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<string>("Jstacode")
                        .IsRequired()
                        .HasColumnName("JSTACODE")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Jtitle")
                        .IsRequired()
                        .HasColumnName("JTITLE")
                        .HasMaxLength(40)
                        .IsUnicode(false);

                    b.Property<string>("Keyuser")
                        .IsRequired()
                        .HasColumnName("KEYUSER")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<string>("Lschmcode")
                        .IsRequired()
                        .HasColumnName("LSCHMCODE")
                        .HasMaxLength(4)
                        .IsUnicode(false);

                    b.Property<decimal>("Lvetocash")
                        .HasColumnName("LVETOCASH")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<decimal>("LyDEpf")
                        .HasColumnName("LY_D_EPF")
                        .HasColumnType("numeric(15, 2)");

                    b.Property<decimal>("LyDTxamt")
                        .HasColumnName("LY_D_TXAMT")
                        .HasColumnType("numeric(15, 2)");

                    b.Property<decimal>("MIncAmt")
                        .HasColumnName("M_INC_AMT")
                        .HasColumnType("numeric(12, 2)");

                    b.Property<DateTime>("MIncDate")
                        .HasColumnName("M_INC_DATE")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Mcall")
                        .HasColumnName("MCALL")
                        .HasColumnType("numeric(9, 2)");

                    b.Property<decimal>("Mcbal")
                        .HasColumnName("MCBAL")
                        .HasColumnType("numeric(6, 2)");

                    b.Property<string>("Meditbl")
                        .IsRequired()
                        .HasColumnName("MEDITBL")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Meps")
                        .IsRequired()
                        .HasColumnName("MEPS")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<decimal>("Mfundall")
                        .HasColumnName("MFUNDALL")
                        .HasColumnType("numeric(10, 2)");

                    b.Property<string>("Mstatus")
                        .IsRequired()
                        .HasColumnName("MSTATUS")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Mstatusod")
                        .IsRequired()
                        .HasColumnName("MSTATUSOD")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("MustprSoc")
                        .IsRequired()
                        .HasColumnName("MUSTPR_SOC")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("NAME")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("National")
                        .IsRequired()
                        .HasColumnName("NATIONAL")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<int>("NmPcb")
                        .HasColumnName("NM_PCB");

                    b.Property<decimal>("Noadvday")
                        .HasColumnName("NOADVDAY")
                        .HasColumnType("numeric(8, 2)");

                    b.Property<int>("Nochild")
                        .HasColumnName("NOCHILD");

                    b.Property<int>("Nppm")
                        .HasColumnName("NPPM");

                    b.Property<string>("Nric")
                        .IsRequired()
                        .HasColumnName("NRIC")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("Nricn")
                        .IsRequired()
                        .HasColumnName("NRICN")
                        .HasMaxLength(22)
                        .IsUnicode(false);

                    b.Property<decimal>("NumChild")
                        .HasColumnName("NUM_CHILD")
                        .HasColumnType("numeric(4, 1)");

                    b.Property<int>("Numchild1")
                        .HasColumnName("NUMCHILD");

                    b.Property<decimal>("OrpLm")
                        .HasColumnName("ORP_LM")
                        .HasColumnType("numeric(13, 4)");

                    b.Property<decimal>("OrpTm")
                        .HasColumnName("ORP_TM")
                        .HasColumnType("numeric(13, 4)");

                    b.Property<string>("OtMaxpay")
                        .IsRequired()
                        .HasColumnName("OT_MAXPAY")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Otcode")
                        .IsRequired()
                        .HasColumnName("OTCODE")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Otraterc")
                        .IsRequired()
                        .HasColumnName("OTRATERC")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Ottbl")
                        .IsRequired()
                        .HasColumnName("OTTBL")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasColumnName("PASSPORT")
                        .HasMaxLength(12)
                        .IsUnicode(false);

                    b.Property<string>("Paymeth")
                        .IsRequired()
                        .HasColumnName("PAYMETH")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Payrtype")
                        .IsRequired()
                        .HasColumnName("PAYRTYPE")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Paystatus")
                        .IsRequired()
                        .HasColumnName("PAYSTATUS")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<int>("PbonusMth")
                        .HasColumnName("PBONUS_MTH");

                    b.Property<string>("Pcb1hd")
                        .IsRequired()
                        .HasColumnName("PCB1HD")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Pcbbyer")
                        .IsRequired()
                        .HasColumnName("PCBBYER")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnName("PHONE")
                        .HasMaxLength(24)
                        .IsUnicode(false);

                    b.Property<string>("Phone2")
                        .IsRequired()
                        .HasColumnName("PHONE2")
                        .HasMaxLength(24)
                        .IsUnicode(false);

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnName("PHOTO")
                        .IsUnicode(false);

                    b.Property<string>("Photodir")
                        .IsRequired()
                        .HasColumnName("PHOTODIR")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Plineno")
                        .IsRequired()
                        .HasColumnName("PLINENO")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnName("POSTCODE")
                        .HasMaxLength(6)
                        .IsUnicode(false);

                    b.Property<DateTime>("PrFrom")
                        .HasColumnName("PR_FROM")
                        .HasColumnType("datetime");

                    b.Property<string>("PrNum")
                        .IsRequired()
                        .HasColumnName("PR_NUM")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("PrRate")
                        .IsRequired()
                        .HasColumnName("PR_RATE")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("PrnEa")
                        .IsRequired()
                        .HasColumnName("PRN_EA")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("PrnIr8s")
                        .IsRequired()
                        .HasColumnName("PRN_IR8S")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("RStatu")
                        .IsRequired()
                        .HasColumnName("R_STATU")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasColumnName("RACE")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Relcode")
                        .IsRequired()
                        .HasColumnName("RELCODE")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnName("REMARK")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int>("Restwkday")
                        .HasColumnName("RESTWKDAY");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnName("SEX")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Shifttbl")
                        .IsRequired()
                        .HasColumnName("SHIFTTBL")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Sitbranch")
                        .IsRequired()
                        .HasColumnName("SITBRANCH")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("Sname")
                        .IsRequired()
                        .HasColumnName("SNAME")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Snric")
                        .IsRequired()
                        .HasColumnName("SNRIC")
                        .HasMaxLength(22)
                        .IsUnicode(false);

                    b.Property<string>("Soaso1hd")
                        .IsRequired()
                        .HasColumnName("SOASO1HD")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Soasobyer")
                        .IsRequired()
                        .HasColumnName("SOASOBYER")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Soasocat")
                        .IsRequired()
                        .HasColumnName("SOASOCAT")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Soasono")
                        .IsRequired()
                        .HasColumnName("SOASONO")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("Soasotbl")
                        .IsRequired()
                        .HasColumnName("SOASOTBL")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Sobso1hd")
                        .IsRequired()
                        .HasColumnName("SOBSO1HD")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Sobsobyer")
                        .IsRequired()
                        .HasColumnName("SOBSOBYER")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Sobsocat")
                        .IsRequired()
                        .HasColumnName("SOBSOCAT")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Sobsono")
                        .IsRequired()
                        .HasColumnName("SOBSONO")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("Sobsotbl")
                        .IsRequired()
                        .HasColumnName("SOBSOTBL")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Socso1hd")
                        .IsRequired()
                        .HasColumnName("SOCSO1HD")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Socsobyer")
                        .IsRequired()
                        .HasColumnName("SOCSOBYER")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Socsocat")
                        .IsRequired()
                        .HasColumnName("SOCSOCAT")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Socsoic")
                        .IsRequired()
                        .HasColumnName("SOCSOIC")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Socsoinit")
                        .IsRequired()
                        .HasColumnName("SOCSOINIT")
                        .HasMaxLength(5)
                        .IsUnicode(false);

                    b.Property<string>("Socsono")
                        .IsRequired()
                        .HasColumnName("SOCSONO")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("Socsotbl")
                        .IsRequired()
                        .HasColumnName("SOCSOTBL")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Sodso1hd")
                        .IsRequired()
                        .HasColumnName("SODSO1HD")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Sodsobyer")
                        .IsRequired()
                        .HasColumnName("SODSOBYER")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Sodsocat")
                        .IsRequired()
                        .HasColumnName("SODSOCAT")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Sodsono")
                        .IsRequired()
                        .HasColumnName("SODSONO")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("Sodsotbl")
                        .IsRequired()
                        .HasColumnName("SODSOTBL")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Soeso1hd")
                        .IsRequired()
                        .HasColumnName("SOESO1HD")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Soesobyer")
                        .IsRequired()
                        .HasColumnName("SOESOBYER")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Soesocat")
                        .IsRequired()
                        .HasColumnName("SOESOCAT")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Soesono")
                        .IsRequired()
                        .HasColumnName("SOESONO")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("Soesotbl")
                        .IsRequired()
                        .HasColumnName("SOESOTBL")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnName("SOURCE")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("Stat11hd")
                        .IsRequired()
                        .HasColumnName("STAT11HD")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnName("STATE")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<bool>("Su")
                        .HasColumnName("SU");

                    b.Property<decimal>("Tempfig1")
                        .HasColumnName("TEMPFIG1")
                        .HasColumnType("numeric(14, 2)");

                    b.Property<decimal>("Tempfig2")
                        .HasColumnName("TEMPFIG2")
                        .HasColumnType("numeric(14, 2)");

                    b.Property<decimal>("Tempfig3")
                        .HasColumnName("TEMPFIG3")
                        .HasColumnType("numeric(14, 2)");

                    b.Property<decimal>("Tempfig4")
                        .HasColumnName("TEMPFIG4")
                        .HasColumnType("numeric(14, 2)");

                    b.Property<string>("Tempstr1")
                        .IsRequired()
                        .HasColumnName("TEMPSTR1")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnName("TOWN")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("Trancode")
                        .IsRequired()
                        .HasColumnName("TRANCODE")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("TxDedSp")
                        .IsRequired()
                        .HasColumnName("TX_DED_SP")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Unempitbl")
                        .IsRequired()
                        .HasColumnName("UNEMPITBL")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Union1hd")
                        .IsRequired()
                        .HasColumnName("UNION1HD")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Unionbyer")
                        .IsRequired()
                        .HasColumnName("UNIONBYER")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Unioncat")
                        .IsRequired()
                        .HasColumnName("UNIONCAT")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Unionno")
                        .IsRequired()
                        .HasColumnName("UNIONNO")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("Uniontbl")
                        .IsRequired()
                        .HasColumnName("UNIONTBL")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnName("UPDATED_ON")
                        .HasColumnType("datetime");

                    b.Property<string>("Weekpay")
                        .IsRequired()
                        .HasColumnName("WEEKPAY")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Whtbl")
                        .IsRequired()
                        .HasColumnName("WHTBL")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Withbopcb")
                        .IsRequired()
                        .HasColumnName("WITHBOPCB")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Withcopcb")
                        .IsRequired()
                        .HasColumnName("WITHCOPCB")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Withhrdf")
                        .IsRequired()
                        .HasColumnName("WITHHRDF")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Withpcb")
                        .IsRequired()
                        .HasColumnName("WITHPCB")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Workgrpid")
                        .IsRequired()
                        .HasColumnName("WORKGRPID")
                        .HasMaxLength(8)
                        .IsUnicode(false);

                    b.Property<DateTime>("WpFrom")
                        .HasColumnName("WP_FROM")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("WpTo")
                        .HasColumnName("WP_TO")
                        .HasColumnType("datetime");

                    b.Property<string>("Wpermit")
                        .IsRequired()
                        .HasColumnName("WPERMIT")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("Empno");

                    b.ToTable("pmast");
                });

            modelBuilder.Entity("EmployeePortal.Models.Family", b =>
                {
                    b.HasOne("EmployeePortal.Models.Pmast", "EmpnoNavigation")
                        .WithMany("Family")
                        .HasForeignKey("Empno")
                        .HasConstraintName("FK_family_pmast");
                });
#pragma warning restore 612, 618
        }
    }
}
